//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class testResult
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public Nullable<int> Hue { get; set; }
        public Nullable<int> Check { get; set; }
    }
}
